image: "ubuntu:latest"

build:
  stage: build
  before_script:
    - apt-get update -y
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install -y make texlive-xetex texlive-latex-extra texlive-lang-other fonts-smc-manjari fonts-smc-uroob fonts-sil-gentium fonts-inconsolata fonts-ubuntu
  script:
    - make
  artifacts:
    paths:
    - report.pdf
